<h1>Pandas</h1>

In [1]:
import pandas as pd
import numpy as np

<h2>5.1 Data structures</h2>

<h3>Series</h3>

In [2]:
obj=pd.Series([1,2,3,4])
obj

0    1
1    2
2    3
3    4
dtype: int64

shows col1=index, col2=values, data type

In [3]:
obj.values

array([1, 2, 3, 4])

In [4]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [5]:
obj2=pd.Series([2,4,6,8],index=['d','c','a','b'])
obj2

d    2
c    4
a    6
b    8
dtype: int64

In [6]:
obj2.index

Index(['d', 'c', 'a', 'b'], dtype='object')

In [7]:
obj2['a']

6

In [8]:
obj2[['b','d']]

b    8
d    2
dtype: int64

In [9]:
obj2[obj2>5]

a    6
b    8
dtype: int64

In [10]:
obj2*2

d     4
c     8
a    12
b    16
dtype: int64

similar to ordered dicts

In [11]:
'b' in obj2

True

In [12]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [13]:
obj3=pd.Series(sdata)

In [14]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [15]:
states = ['California', 'Ohio', 'Oregon', 'Texas']

In [16]:
obj4=pd.Series(sdata,index=states)

In [17]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [18]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [19]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [20]:
obj3+obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [21]:
obj4.name='population'
obj4.index.name='state'

In [22]:
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

<h3>Dataframe</h3>

In [23]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
'year': [2000, 2001, 2002, 2001, 2002, 2003],
'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame=pd.DataFrame(data)

In [24]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [25]:
frame.head(7)

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [26]:
pd.DataFrame(data,columns=['year','state','pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [27]:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'],index=['one', 'two', 'three', 'four',
'five', 'six'])

In [28]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [29]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [30]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [31]:
frame2.year # to select ac column,returns a column Series (index,values,name)

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [32]:
frame2.loc['three'] # to select a row, returns a row Series (indexes ar column names, name is row index)

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [33]:
frame2['debt']=10 #assign a value to a whole column

In [34]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5    10
two    2001    Ohio  1.7    10
three  2002    Ohio  3.6    10
four   2001  Nevada  2.4    10
five   2002  Nevada  2.9    10
six    2003  Nevada  3.2    10

In [35]:
frame2['debt']=np.arange(6.) # assign a range of values

In [36]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

In [37]:
val=pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])

In [38]:
frame2['debt']=val
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [39]:
frame2['eastern']=frame2.state=='Ohio' # add a column based on a boolean value
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

In [40]:
del frame2['eastern']
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [41]:
# if dict of dicts
pop = {'Nevada': {2001: 2.4, 2002: 2.9},'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [42]:
frame3=pd.DataFrame(pop)
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [43]:
#transpose
frame3.T

2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

In [44]:
frame3.index.name='year'
frame3.columns.name='state'
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

<h3>Index objects</h3>

In [45]:
# is an object Series_like itself, inmutable
obj=pd.Series(range(3), index=['a','b','c'])
index=obj.index

In [46]:
index

Index(['a', 'b', 'c'], dtype='object')

In [47]:
index[1:]

Index(['b', 'c'], dtype='object')

In [48]:
#index[1]='d'

In [49]:
labels=pd.Index(np.arange(3))
labels

Int64Index([0, 1, 2], dtype='int64')

In [50]:
obj2=pd.Series([1.4,-9.4,0],index=labels)
obj2

0    1.4
1   -9.4
2    0.0
dtype: float64

In [51]:
obj2.index is labels

True

Index behave like python sets but allows repeated elemens. Functions: append, difference, intersection, union...

<h2>5.2 Essential functionality</h2>

<h3>Reindexing</h3>

In [52]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [53]:
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e']) # reorders existing values and fills with NaN missing values
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [54]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])
obj3

0      blue
2    purple
4    yellow
dtype: object

In [55]:
obj3.reindex(range(6),method='ffill') # for filling values of missing indexes

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [56]:
frame=pd.DataFrame(np.arange(9).reshape((3,3)),index=['a','c','d'],columns=['Ohio','Texas','California'])
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [57]:
frame2=frame.reindex(['a', 'b', 'c', 'd'])
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [58]:
states = ['Texas', 'Utah', 'California']
frame.reindex(columns=states) # can be applied to columns

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

<h3>Drop entries from axis</h3>

In [59]:
obj=pd.Series(np.arange(5.),index=['a', 'b', 'c', 'd', 'e'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [60]:
new_obj=obj.drop('c')
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [61]:
# inplace modifies data definetly and DESTROYS dropped values
obj.drop('c',inplace=True)
obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [62]:
data=pd.DataFrame(np.arange(16).reshape(4,4),index=['Ohio', 'Colorado', 'Utah', 'New York'],columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [63]:
data.drop(['Colorado', 'Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [64]:
data.drop('two',axis=1) # important: axis=1

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

<H3>Indexing, selection and filtering</h3>

In [65]:
obj = pd.Series(np.arange(4.),index=['a', 'b', 'c', 'd'])

In [66]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [67]:
obj['b']

1.0

In [68]:
obj[1]

1.0

In [69]:
obj[2:]

c    2.0
d    3.0
dtype: float64

In [70]:
obj[[1,3]]

b    1.0
d    3.0
dtype: float64

In [71]:
obj[obj<2]

a    0.0
b    1.0
dtype: float64

In [72]:
# slicing with labels INCLUDES the end point
obj['b':'c']

b    1.0
c    2.0
dtype: float64

In [73]:
data=pd.DataFrame(np.arange(16).reshape(4,4),index=['Ohio', 'Colorado', 'Utah', 'New York'],columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [74]:
data['two']
# Beware of the difference:
#   data['two'] returns column 'two' as a Series
#   data.loc['val'] search ROW with 'val' index
#   data.loc[:,'two'] returns column 'two' as a Series

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int64

In [75]:
data[['three','one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [76]:
# EXCEPTION:passing a range (:2) refers to rows, passing single elements or lists refers to columns
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [77]:
data<5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [78]:
data[data<5]=0

In [79]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [80]:
# LOC and ILOC for slicing index labels (loc) or integers (iloc)
data.loc['Colorado', ['two', 'three']] 
# (i)loc[rows_list, columns_list]

two      5
three    6
Name: Colorado, dtype: int64

In [81]:
data.iloc[2,[3,0,1]] 
# if single column returns a Series object (index=rows_list,values,name=column selected)

four    11
one      8
two      9
Name: Utah, dtype: int64

In [82]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int64

In [83]:
data.iloc[1:3]
# if RANGE ([:2],no list), returns rows selected

one  two  three  four
Colorado    0    5      6     7
Utah        8    9     10    11

In [84]:
data.loc[:'Utah','two']
# same for loc but includes the last element of the range too

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int64

In [85]:
data.iloc[:,:3]

one  two  three
Ohio        0    0      0
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

In [86]:
data.iloc[:,:3][data.three>5]

one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

<h3>Integer indexes</h3>

In [87]:
#if no labels are assigned as indexes, [-1] selection wont work
ser=pd.Series(np.arange(3.))
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [88]:
#ser[-1] #throws an error

In [89]:
ser2 = pd.Series(np.arange(3.), index=['a', 'b', 'c'])
ser2[-1]
# no error with non-integer index

2.0

In [90]:
ser[:1]

0    0.0
dtype: float64

In [91]:
ser.loc[:1]
# remember, loc includes the last element of the range
# better use iloc for integers and loc for labels

0    0.0
1    1.0
dtype: float64

In [92]:
ser.iloc[:1]

0    0.0
dtype: float64

<h3>Arithmetic and data alignment</h3>

In [93]:
# arithmetics work with indexes (join)
s1=pd.Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])
s2=pd.Series([-2.1, 3.6, -1.5, 4, 3.1], index=['a', 'c', 'e', 'f', 'g'])
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [94]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [95]:
s1+s2
# indexes must be present in BOTH to be operated

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [96]:
df1=pd.DataFrame(np.arange(9).reshape(3,3),columns=list('bcd'),index=['Ohio', 'Texas', 'Colorado'])
df2=pd.DataFrame(np.arange(12.).reshape(4,3),columns=list('bde'),index=['Utah', 'Ohio', 'Texas', 'Oregon'])
df1

b  c  d
Ohio      0  1  2
Texas     3  4  5
Colorado  6  7  8

In [97]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [98]:
df1+df2
# indexes for ROWS and COLUMNS must be in BOTH dataframes

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [99]:
df1=pd.DataFrame({'A':[1,2]})
df2=pd.DataFrame({'B':[3,4]})
df1

A
0  1
1  2

In [100]:
df2

B
0  3
1  4

In [101]:
df1+df2

A   B
0 NaN NaN
1 NaN NaN

In [102]:
df1-df2

A   B
0 NaN NaN
1 NaN NaN

<h4>Arithmetic methods with fill values</h4>

In [103]:
df1=pd.DataFrame(np.arange(12.).reshape(3,4),columns=list('abcd'))
df2=pd.DataFrame(np.arange(20.).reshape(4,5),columns=list('abcde'))
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [104]:
df2.loc[1,'b']=np.nan
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [105]:
df1+df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [106]:
# add method with fill_value=0
df1.add(df2,fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [107]:
df1.sub(df2)

a    b    c    d   e
0  0.0  0.0  0.0  0.0 NaN
1 -1.0  NaN -1.0 -1.0 NaN
2 -2.0 -2.0 -2.0 -2.0 NaN
3  NaN  NaN  NaN  NaN NaN

In [108]:
df2.sub(df1,fill_value=0)

a     b     c     d     e
0   0.0   0.0   0.0   0.0   4.0
1   1.0  -5.0   1.0   1.0   9.0
2   2.0   2.0   2.0   2.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [109]:
df1.rsub(df2,fill_value=0)
# r before method swaps df1 and df2

a     b     c     d     e
0   0.0   0.0   0.0   0.0   4.0
1   1.0  -5.0   1.0   1.0   9.0
2   2.0   2.0   2.0   2.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [110]:
df1.mul(df2,fill_value=1)

a     b      c      d     e
0   0.0   1.0    4.0    9.0   4.0
1  20.0   5.0   42.0   56.0   9.0
2  80.0  99.0  120.0  143.0  14.0
3  15.0  16.0   17.0   18.0  19.0

<h4>Operations between df an series</h4>

In [111]:
arr=np.arange(12.).reshape(3,4)
arr


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [112]:
arr[0]

array([0., 1., 2., 3.])

In [113]:
arr-arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [114]:
frame=pd.DataFrame(np.arange(12.).reshape(4,3),columns=list('bde'),index=['Utah', 'Ohio', 'Texas', 'Oregon'])
series=frame.iloc[0]
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [115]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [116]:
frame-series
# arithmetic operation with values (in oposition to .drop('Utah')

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [117]:
series2=pd.Series(range(3),index=list('bef'))
series2

b    0
e    1
f    2
dtype: int64

In [118]:
frame+series2
# series2 has no column 'name', + acts as union

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [119]:
series3=frame['d']
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [120]:
frame.sub(series3)

Ohio  Oregon  Texas  Utah   b   d   e
Utah     NaN     NaN    NaN   NaN NaN NaN NaN
Ohio     NaN     NaN    NaN   NaN NaN NaN NaN
Texas    NaN     NaN    NaN   NaN NaN NaN NaN
Oregon   NaN     NaN    NaN   NaN NaN NaN NaN

In [121]:
frame.sub(series3,axis=0)
# broadcast for all of the columns

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

<h3>Function application and mapping</h3>

In [122]:
frame=pd.DataFrame(np.random.randn(4,3),columns=list('bde'),index=['Utah', 'Ohio', 'Texas', 'Oregon'])
frame

b         d         e
Utah   -0.432762 -0.738492  1.608408
Ohio    0.319012 -0.070988  0.565986
Texas   1.837838  1.420480  1.469976
Oregon  0.681980  0.463951  0.658572

In [123]:
# numpy ufuncs work on pandas
np.abs(frame)

b         d         e
Utah    0.432762  0.738492  1.608408
Ohio    0.319012  0.070988  0.565986
Texas   1.837838  1.420480  1.469976
Oregon  0.681980  0.463951  0.658572

In [124]:
f = lambda x:x.max()-x.min()

In [125]:
frame.apply(f)
# f applied to each column

b    2.270600
d    2.158972
e    1.042421
dtype: float64

In [126]:
frame.apply(f, axis=1)
# f applied to each row

Utah      2.346900
Ohio      0.636974
Texas     0.417358
Oregon    0.218029
dtype: float64

In [127]:
# functions can return series
def f(x):
    return pd.Series([x.max(),x.min()],index=['max','min'])

In [128]:
frame.apply(f)

b         d         e
max  1.837838  1.420480  1.608408
min -0.432762 -0.738492  0.565986

In [129]:
frame.apply(f, axis='columns')

max       min
Utah    1.608408 -0.738492
Ohio    0.565986 -0.070988
Texas   1.837838  1.420480
Oregon  0.681980  0.463951

In [130]:
# element-wise functions applied with applymap
format=lambda x: '%.2f' % x

In [131]:
frame.applymap(format)

b      d     e
Utah    -0.43  -0.74  1.61
Ohio     0.32  -0.07  0.57
Texas    1.84   1.42  1.47
Oregon   0.68   0.46  0.66

In [132]:
# if is a Series, .map method
frame['e'].map(format)

Utah      1.61
Ohio      0.57
Texas     1.47
Oregon    0.66
Name: e, dtype: object

<h3>Sorting and ranking</h3>

In [133]:
# Sort_index
obj=pd.Series(range(4),index=['d', 'a', 'b', 'c'])
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [134]:
frame=pd.DataFrame(np.arange(8).reshape(2,4),index=['three','one'],columns=['d', 'a', 'b', 'c'])
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [136]:
frame.sort_index(axis=1)
# sort columns

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [137]:
frame.sort_index(axis=1,ascending=False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [138]:
# Sort_values
obj=pd.Series([4, 7, -3, 2])
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [139]:
obj=pd.Series([4, np.nan, 7, np.nan, -3, 2])
obj.sort_values() # NaN are placed last

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [141]:
frame=pd.DataFrame({'b': [4, 7, -3, 2], 'a': [0, 1, 0, 1]})
frame.sort_values(by='b') # select the column to sort (can select several)

b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [145]:
# rank() sorts and ranks?? -> Create groups of values from 1 to len(obj)
obj=pd.Series([7, -5, 7, 4, 2, 0, 4])
#print(obj.sort_values())
print(obj.rank())

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64


In [144]:
# accepts several methods
obj.rank(method='first') #??

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [146]:
frame=pd.DataFrame({'b': [4.3, 7, -3, 2], 'a': [0, 1, 0, 1],'c': [-2, 5, 8, -2.5]})
frame

b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

In [147]:
frame.rank(axis=1)

b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

<h3>Axis indexes with duplicate labels</h3>

In [148]:
# BEWARE
obj = pd.Series(range(5), index=['a', 'a', 'b', 'b', 'c'])
obj.index.is_unique

False

In [150]:
print(obj['a'])
print(obj['c'])

a    0
a    1
dtype: int64
4


<h2>5.3 Summarizing and computing descriptive statistics</h2>

In [151]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5],[np.nan, np.nan], [0.75, -1.3]],index=['a', 'b', 'c', 'd'],columns=['one', 'two'])
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [155]:
# There are summarizing, index related, acummulative methods... see table 5-8!!
# sum()
print(df.sum())
print(df.sum(axis=1))
print(df.sum(axis=1,skipna=False)) # by default skips NaN

one    9.25
two   -5.80
dtype: float64
a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64
a     NaN
b    2.60
c     NaN
d   -0.55
dtype: float64


In [157]:
# count (non NaN values)
print(df.count())
print(df.count(axis=1))

one    3
two    2
dtype: int64
a    1
b    2
c    0
d    2
dtype: int64


In [159]:
# min, max
print(df.min())
print(df.max(axis=1))

one    0.75
two   -4.50
dtype: float64
a    1.40
b    7.10
c     NaN
d    0.75
dtype: float64


In [163]:
# cumsum
print(df.cumsum())
print(df.cumsum(axis=1))

    one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8
    one   two
a  1.40   NaN
b  7.10  2.60
c   NaN   NaN
d  0.75 -0.55


In [164]:
# median
print(df.median(),df.median(axis=1))

one    1.4
two   -2.9
dtype: float64 a    1.400
b    1.300
c      NaN
d   -0.275
dtype: float64


In [165]:
# indexes
print(df.idxmin(),df.idxmax(axis=1))

one    d
two    b
dtype: object a    one
b    one
c    NaN
d    one
dtype: object


In [160]:
# describe
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

<h3>Correlation and covariance</h3>

In [171]:
import pandas_datareader.data as pdr
all_data={ticker: pdr.get_data_yahoo(ticker) for ticker in ['AAPL', 'IBM', 'MSFT', 'GOOG']}
price=pd.DataFrame({ticker:data['Adj Close'] for ticker, data in all_data.items()})
volume=pd.DataFrame({ticker:data['Volume'] for ticker,data in all_data.items()})
returns=price.pct_change()
returns.tail()

AAPL       IBM      MSFT      GOOG
Date                                              
2022-01-05 -0.026600  0.001449 -0.038388 -0.046830
2022-01-06 -0.016693 -0.020836 -0.007902 -0.000745
2022-01-07  0.000988 -0.003768  0.000510 -0.003973
2022-01-10  0.000116  0.001483  0.000732  0.011456
2022-01-11  0.016784 -0.015996  0.002259  0.010417

In [173]:
# Correlation between two columns
returns['MSFT'].corr(returns["IBM"])

0.4949169751523445

In [174]:
# Correlation Matrix
returns.corr()

AAPL       IBM      MSFT      GOOG
AAPL  1.000000  0.429552  0.737071  0.659425
IBM   0.429552  1.000000  0.494917  0.466201
MSFT  0.737071  0.494917  1.000000  0.778926
GOOG  0.659425  0.466201  0.778926  1.000000

In [176]:
# Covariance
print(returns['MSFT'].cov(returns["IBM"]))
returns.cov()

0.0001428154105821416


AAPL       IBM      MSFT      GOOG
AAPL  0.000370  0.000137  0.000246  0.000216
IBM   0.000137  0.000276  0.000143  0.000132
MSFT  0.000246  0.000143  0.000302  0.000231
GOOG  0.000216  0.000132  0.000231  0.000291

<h3>Unique values, value count and membership</h3>

In [180]:
# Unique values
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c'])
uniques=obj.unique()
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

In [181]:
# Unique values frequencies
obj.value_counts() #sorted by default

c    3
a    3
b    2
d    1
dtype: int64

In [182]:
pd.value_counts(obj.values, sort=False) # to mantain index sorting

c    3
a    3
d    1
b    2
dtype: int64

In [185]:
# isin for checking membership and extracting boolean maps
mask = obj.isin(['b','c'])
print(mask,obj[mask])

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool 0    c
5    b
6    b
7    c
8    c
dtype: object


In [186]:
# Index.get_indexer returns a index number matrix from matching values
to_match=pd.Series(['c', 'a', 'b', 'b', 'c', 'a'])
unique_vals=pd.Series(['c', 'b', 'a'])
pd.Index(unique_vals).get_indexer(to_match)

array([0, 2, 1, 1, 0, 2])